export const AppColors = {
  tabBarActive: '#C88CEB',
  tabBarInactiveLight: '#D8BEEB',
  tabBarInactiveDarkMap: '#F3E9FF',
  primary: '#9D8DF1',
  mapSheetSendLocationButton: '#C4B5F7',
  navy: '#19395A',
  textBody: '#25496E',
  muted: '#6A8298',
  placeholder: '#6F8599',
  border: '#D6DCE3',
  inputBg: '#F9FBFF',
  white: '#FFFFFF',
  tagBg: '#EDE8FF',
} as const;
